kind: pipeline
name: neu-axentix new release

steps:
- name: install
  image: node:14-alpine
  commands:
  - apk add python make g++
  - npm install
  when:
    event:
      - tag

- name: build
  image: node:14-alpine
  commands:
  - npm run build
  when:
    event:
      - tag

- name: make zip folder
  image: node:14-alpine
  commands:
  - apk add zip
  - cp -R ./dist ./neu-axentix-v${DRONE_TAG}
  - cp CHANGELOG.md ./neu-axentix-v${DRONE_TAG}/CHANGELOG.md
  - cp LICENSE ./neu-axentix-v${DRONE_TAG}/LICENSE
  - cp README.md ./neu-axentix-v${DRONE_TAG}/README.md
  - zip -r ./neu-axentix-v${DRONE_TAG}.zip ./neu-axentix-v${DRONE_TAG}
  when:
    event:
      - tag

- name: github release
  image: plugins/github-release
  settings:
    api_key:
      from_secret: github_auth
    files:
      - neu-axentix-v${DRONE_TAG}.zip
  when:
    event:
      - tag

- name: publish to npm
  image: plugins/npm
  settings:
    token:
      from_secret: npm_token
    email:
      from_secret: publish_email
  when:
    event:
      - tag