---
name: create-labels

on:
  push:
    branches:
      - v2
    paths:
      - .github/labels.yml
      - .github/workflows/create-labels.yml

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: micnncim/action-label-syncer@v1
        with:
          manifest: .github/labels.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}